# NumPy

In [8]:
import numpy as np

Converting list into array (Vectorized Operaion)

In [9]:
list1 = np.array([[1, 2, 3], [4, 5, 5], [7, 8, 9]])
list2 = np.array([[9, 3, 2], [4, 5, 4], [3, 8, 3]])
result = list1 + list2
print(result)

[[10  5  5]
 [ 8 10  9]
 [10 16 12]]
